fields:
  ClientAppUsed:
    target: '''Application Name'''
    role: resource
  MailboxOwnerUPN:
    target: '''User Name'''
    role: subject
  OfficeWorkload:
    target: '''Application Name'''
    role: resource
  OrganizationName:
    target: '''Resource Name'''
    role: resource
  ClientInfoString:
    target: '''User Agent'''
    role: network
  UserType:
    target: Type
    role: subject
  EmailDirection:
    target: Direction
    role: resource
  RecipientEmailAddress:
    target: '''Target User Name'''
    role: target
  SenderFromAddress:
    target: '''User Name'''
    role: subject
