x-azure-as-is-custom: &azure_as_is_custom
  category: azure_custom
  service: sentinel_workspace_custom
  sources:
  - Azure Log Analytics Custom Logs
  - SOC Application Logs

tables:
  AADSignInEventsBeta: *azure_as_is_custom
  ADFSSignInLogs: *azure_as_is_custom
  AGWFirewallLogs: *azure_as_is_custom
  AIAgentsInfo: *azure_as_is_custom
  AIShield: *azure_as_is_custom
  ARGOS_CL: *azure_as_is_custom
  ASimNetworkSessionSonicWallFirewall: *azure_as_is_custom
  AWSGuardDuty: *azure_as_is_custom
  AWSSecurityHubFindings: *azure_as_is_custom
  AZFWApplicationRule: *azure_as_is_custom
  AZFWFlowTrace: *azure_as_is_custom
  AZFWIdpsSignature: *azure_as_is_custom
  AZFWNetworkRule: *azure_as_is_custom
  AZFWThreatIntel: *azure_as_is_custom
  AZFWDnsQuery: *azure_as_is_custom
  AlertEvidence: *azure_as_is_custom
  Alerts_advisory: *azure_as_is_custom
  Alerts_assets: *azure_as_is_custom
  Alerts_bit_bucket: *azure_as_is_custom
  Alerts_cloud_storage: *azure_as_is_custom
  Alerts_compromised_endpoints_cookies: *azure_as_is_custom
  Alerts_compromised_files: *azure_as_is_custom
  Alerts_cyber_crime_forums: *azure_as_is_custom
  Alerts_darkweb_data_breaches: *azure_as_is_custom
  Alerts_darkweb_marketplaces: *azure_as_is_custom
  Alerts_darkweb_ransomware: *azure_as_is_custom
  Alerts_defacement_content: *azure_as_is_custom
  Alerts_defacement_keyword: *azure_as_is_custom
  Alerts_defacement_url: *azure_as_is_custom
  Alerts_discord: *azure_as_is_custom
  Alerts_docker: *azure_as_is_custom
  Alerts_domain_expiry: *azure_as_is_custom
  Alerts_domain_watchlist: *azure_as_is_custom
  Alerts_flash_report: *azure_as_is_custom
  Alerts_github: *azure_as_is_custom
  Alerts_hacktivism: *azure_as_is_custom
  Alerts_i2p: *azure_as_is_custom
  Alerts_iocs: *azure_as_is_custom
  Alerts_ip_risk_score: *azure_as_is_custom
  Alerts_leaked_credentials: *azure_as_is_custom
  Alerts_malicious_ads: *azure_as_is_custom
  Alerts_mobile_apps: *azure_as_is_custom
  Alerts_new_vulnerability: *azure_as_is_custom
  Alerts_news_feed: *azure_as_is_custom
  Alerts_osint: *azure_as_is_custom
  Alerts_ot_ics: *azure_as_is_custom
  Alerts_pastebin: *azure_as_is_custom
  Alerts_phishing: *azure_as_is_custom
  Alerts_physical_threats: *azure_as_is_custom
  Alerts_postman: *azure_as_is_custom
  Alerts_product_vulnerability: *azure_as_is_custom
  Alerts_social_media_monitoring: *azure_as_is_custom
  Alerts_ssl_expiry: *azure_as_is_custom
  Alerts_stealer_logs: *azure_as_is_custom
  Alerts_subdomains: *azure_as_is_custom
  Alerts_suspicious_domains: *azure_as_is_custom
  Alerts_telegram_mentions: *azure_as_is_custom
  Alerts_tor_links: *azure_as_is_custom
  Alerts_vulnerability: *azure_as_is_custom
  Alerts_web_applications: *azure_as_is_custom
  Anomalies: *azure_as_is_custom
  Anvilogic_Alerts_CL: *azure_as_is_custom
  AppServiceAntivirusScanAuditLogs: *azure_as_is_custom
  Armorblox_CL: *azure_as_is_custom
  Authomize_v2_CL: *azure_as_is_custom
  BHEAttackPathsData_CL: *azure_as_is_custom
  BehaviorAnalytics: *azure_as_is_custom
  BitSightAlerts: *azure_as_is_custom
  BitSightBreaches: *azure_as_is_custom
  BitSightFindingsData: *azure_as_is_custom
  BitSightGraphData: *azure_as_is_custom
  Bitglass: *azure_as_is_custom
  CBSLog: *azure_as_is_custom
  CarbonBlackEvents_CL: *azure_as_is_custom
  CarbonBlackNotifications_CL: *azure_as_is_custom
  CiscoSEGEvent: *azure_as_is_custom
  CiscoSecureEndpoint_CL: *azure_as_is_custom
  CiscoSyslogUTD: *azure_as_is_custom
  ClarotyEvent: *azure_as_is_custom
  CognniIncidents_CL: *azure_as_is_custom
  CommvaultAlerts_CL: *azure_as_is_custom
  ContrastADRAttackEvents_CL: *azure_as_is_custom
  ContrastADRIncidents_CL: *azure_as_is_custom
  CopilotActivity: *azure_as_is_custom
  CortexXDR_Incidents_CL: *azure_as_is_custom
  CrowdStrikeFalconEventStream: *azure_as_is_custom
  CyberArk_AuditEvents_CL: *azure_as_is_custom
  CyberSixgill_Alerts_CL: *azure_as_is_custom
  CyberpionActionItems_CL: *azure_as_is_custom
  CyfirmaASCertificatesAlerts_CL: *azure_as_is_custom
  CyfirmaASCloudWeaknessAlerts_CL: *azure_as_is_custom
  CyfirmaASConfigurationAlerts_CL: *azure_as_is_custom
  CyfirmaASDomainIPReputationAlerts_CL: *azure_as_is_custom
  CyfirmaASDomainIPVulnerabilityAlerts_CL: *azure_as_is_custom
  CyfirmaASOpenPortsAlerts_CL: *azure_as_is_custom
  CyfirmaBIDomainITAssetAlerts_CL: *azure_as_is_custom
  CyfirmaBIExecutivePeopleAlerts_CL: *azure_as_is_custom
  CyfirmaBIMaliciousMobileAppsAlerts_CL: *azure_as_is_custom
  CyfirmaBIProductSolutionAlerts_CL: *azure_as_is_custom
  CyfirmaBISocialHandlersAlerts_CL: *azure_as_is_custom
  CyfirmaCompromisedAccounts_CL: *azure_as_is_custom
  CyfirmaDBWMDarkWebAlerts_CL: *azure_as_is_custom
  CyfirmaDBWMPhishingAlerts_CL: *azure_as_is_custom
  CyfirmaDBWMRansomwareAlerts_CL: *azure_as_is_custom
  CyfirmaIndicators_CL: *azure_as_is_custom
  CyfirmaSPEConfidentialFilesAlerts_CL: *azure_as_is_custom
  CyfirmaSPEPIIAndCIIAlerts_CL: *azure_as_is_custom
  CyfirmaSPESocialThreatAlerts_CL: *azure_as_is_custom
  CyfirmaSPESourceCodeAlerts_CL: *azure_as_is_custom
  CyfirmaVulnerabilities_CL: *azure_as_is_custom
  CynerioEvent_CL: *azure_as_is_custom
  Cyren_Indicators_CL: *azure_as_is_custom
  D3SOARIncidents_CL: *azure_as_is_custom
  DataminrPulseAlerts: *azure_as_is_custom
  DataverseActivity: *azure_as_is_custom
  DataverseSharePointSites: *azure_as_is_custom
  DefendAuditData: *azure_as_is_custom
  DeviceFileCertificateInfo: *azure_as_is_custom
  DeviceInfo: *azure_as_is_custom
  DeviceNetworkInfo: *azure_as_is_custom
  DeviceRegistryEvents: *azure_as_is_custom
  DeviceTvmInfoGathering: *azure_as_is_custom
  DeviceTvmSecureConfigurationAssessment: *azure_as_is_custom
  DeviceTvmSoftwareInventory: *azure_as_is_custom
  DeviceTvmSoftwareVulnerabilities: *azure_as_is_custom
  DeviceTvmSoftwareVulnerabilitiesKB: *azure_as_is_custom
  DigitalGuardianDLPEvent: *azure_as_is_custom
  DragosNotificationsToSentinel: *azure_as_is_custom
  DuoSecurityTrustMonitor_CL: *azure_as_is_custom
  DynatraceAttacks: *azure_as_is_custom
  DynatraceProblems: *azure_as_is_custom
  DynatraceSecurityProblems: *azure_as_is_custom
  ESETPROTECT: *azure_as_is_custom
  EgressDefend_CL: *azure_as_is_custom
  EmailAttachmentInfo: *azure_as_is_custom
  EmailPostDeliveryEvents: *azure_as_is_custom
  Entities_Data_CL: *azure_as_is_custom
  ExchangeAdminAuditLogs: *azure_as_is_custom
  ExtraHopDetections: *azure_as_is_custom
  FinanceOperationsActivity_CL: *azure_as_is_custom
  FireworkV2_CL: *azure_as_is_custom
  ForescoutHostProperties_CL: *azure_as_is_custom
  Fortiweb: *azure_as_is_custom
  GitHubAudit: *azure_as_is_custom
  GitHubRepo: *azure_as_is_custom
  GitLabAudit: *azure_as_is_custom
  GoogleCloudSCC: *azure_as_is_custom
  Guardian: *azure_as_is_custom
  HackerViewLog: *azure_as_is_custom
  Heartbeat: *azure_as_is_custom
  IdentityDirectoryEvents: *azure_as_is_custom
  IdentityInfo: *azure_as_is_custom
  IdentityLogonEvents: *azure_as_is_custom
  IdentityQueryEvents: *azure_as_is_custom
  Illumio_Auditable_Events_CL: *azure_as_is_custom
  Infoblox: *azure_as_is_custom
  InfobloxCDC: *azure_as_is_custom
  InfobloxCDC_SOCInsights: *azure_as_is_custom
  InfobloxInsight: *azure_as_is_custom
  Infoblox_dnsclient: *azure_as_is_custom
  InformationProtectionLogs_CL: *azure_as_is_custom
  JamfProtectThreatEvents: *azure_as_is_custom
  JamfProtectUnifiedLogs: *azure_as_is_custom
  KeeperSecurityEventNewLogs_CL: *azure_as_is_custom
  KnowBe4Defend_CL: *azure_as_is_custom
  LAQueryLogs: *azure_as_is_custom
  LastPassNativePoller_CL: *azure_as_is_custom
  LookoutEvents: *azure_as_is_custom
  Lookout_CL: *azure_as_is_custom
  MSBizAppsTerminatedEmployees: *azure_as_is_custom
  MailGuard365_Threats_CL: *azure_as_is_custom
  MessageEvents: *azure_as_is_custom
  MessageUrlInfo: *azure_as_is_custom
  MimecastAudit: *azure_as_is_custom
  MimecastAudit_CL: *azure_as_is_custom
  MimecastCG: *azure_as_is_custom
  MimecastDLP: *azure_as_is_custom
  MimecastDLP_CL: *azure_as_is_custom
  MimecastSIEM_CL: *azure_as_is_custom
  MimecastTTPAttachment: *azure_as_is_custom
  MimecastTTPAttachment_CL: *azure_as_is_custom
  MimecastTTPImpersonation: *azure_as_is_custom
  MimecastTTPImpersonation_CL: *azure_as_is_custom
  MimecastTTPUrl: *azure_as_is_custom
  MimecastTTPUrl_CL: *azure_as_is_custom
  MorphisecAlerts_CL: *azure_as_is_custom
  NetBackupAlerts_CL: *azure_as_is_custom
  Netclean_Incidents_CL: *azure_as_is_custom
  NetskopeWebTransactions_CL: *azure_as_is_custom
  NetskopeWebtxErrors_CL: *azure_as_is_custom
  NetworkAccessTraffic: *azure_as_is_custom
  NordPassEventLogs_CL: *azure_as_is_custom
  OktaSSO: *azure_as_is_custom
  OnePasswordEventLogs_CL: *azure_as_is_custom
  OracleDatabaseAuditEvent: *azure_as_is_custom
  PingFederateEvent: *azure_as_is_custom
  PowerAutomateActivity: *azure_as_is_custom
  ProofPointTAPClicksPermittedV2_CL: *azure_as_is_custom
  ProofPointTAPMessagesDeliveredV2_CL: *azure_as_is_custom
  ProofpointPOD: *azure_as_is_custom
  PulseConnectSecure: *azure_as_is_custom
  PurviewDataSensitivityLogs: *azure_as_is_custom
  QualysHostDetection: *azure_as_is_custom
  RSAIDPlus_AdminLogs_CL: *azure_as_is_custom
  RadiflowEvent: *azure_as_is_custom
  RecordedFutureIdentity_PlaybookAlertResults_CL: *azure_as_is_custom
  RedCanaryDetections_CL: *azure_as_is_custom
  Rubrik_Anomaly_Data_CL: *azure_as_is_custom
  Rubrik_Events_Data_CL: *azure_as_is_custom
  SAPBTPAuditLog_CL: *azure_as_is_custom
  SAPETDAlerts_CL: *azure_as_is_custom
  SAPETDInvestigations_CL: *azure_as_is_custom
  SAPLogServ_CL: *azure_as_is_custom
  SINECSecurityGuard_CL: *azure_as_is_custom
  SOCPrimeAuditLogs_CL: *azure_as_is_custom
  SOCRadarAuditLog_CL: *azure_as_is_custom
  SOCRadar_Alarms_CL: *azure_as_is_custom
  SQLEvent: *azure_as_is_custom
  SailPointIDN_Events_CL: *azure_as_is_custom
  SailPointIDN_Triggers_CL: *azure_as_is_custom
  SalesforceServiceCloud: *azure_as_is_custom
  Samsung_Knox_Audit_CL: *azure_as_is_custom
  Samsung_Knox_Process_CL: *azure_as_is_custom
  Samsung_Knox_System_CL: *azure_as_is_custom
  Samsung_Knox_User_CL: *azure_as_is_custom
  SecurityIncident: *azure_as_is_custom
  SecurityNestedRecommendation: *azure_as_is_custom
  SecurityRecommendation: *azure_as_is_custom
  SecurityRegulatoryCompliance: *azure_as_is_custom
  SenservaPro_CL: *azure_as_is_custom
  Sonrai_Tickets_CL: *azure_as_is_custom
  SophosXGFirewall: *azure_as_is_custom
  SpyCloudBreachDataWatchlist_CL: *azure_as_is_custom
  StorageBlobLogs: *azure_as_is_custom
  StorageFileLogs: *azure_as_is_custom
  SymantecEndpointProtection: *azure_as_is_custom
  SymantecProxySG: *azure_as_is_custom
  SymantecVIP: *azure_as_is_custom
  TacitRed_Findings_CL: *azure_as_is_custom
  TheomAlerts_CL: *azure_as_is_custom
  ThreatIntelIndicators: *azure_as_is_custom
  ThreatIntelligenceIndicator: *azure_as_is_custom
  TrendMicro_XDR_WORKBENCH_CL: *azure_as_is_custom
  UbiquitiAuditEvent: *azure_as_is_custom
  VMConnection: *azure_as_is_custom
  VMwareESXi: *azure_as_is_custom
  VMware_CWS_DLPLogs_CL: *azure_as_is_custom
  VMware_CWS_Weblogs_CL: *azure_as_is_custom
  VMware_SDWAN_FirewallLogs_CL: *azure_as_is_custom
  VMware_VECO_EventLogs_CL: *azure_as_is_custom
  Vaikora_AgentSignals_CL: *azure_as_is_custom
  Vaikora_SecurityAlerts_CL: *azure_as_is_custom
  ValenceAlert_CL: *azure_as_is_custom
  ValimailEnforceEvents_CL: *azure_as_is_custom
  VectraDetections: *azure_as_is_custom
  VeeamMalwareEvents_CL: *azure_as_is_custom
  VeeamOneTriggeredAlarms_CL: *azure_as_is_custom
  VeeamSecurityComplianceAnalyzer_CL: *azure_as_is_custom
  VeeamSessions_CL: *azure_as_is_custom
  Veeam_GetFinishedConfigurationBackupSessions: *azure_as_is_custom
  Veeam_GetJobFinished: *azure_as_is_custom
  Veeam_GetSecurityEvents: *azure_as_is_custom
  VersasecCmsSysLogs: *azure_as_is_custom
  W3CIISLog: *azure_as_is_custom
  WireData: *azure_as_is_custom
  XbowAssets_CL: *azure_as_is_custom
  XbowFindings_CL: *azure_as_is_custom
  ZNSegmentAudit: *azure_as_is_custom
  ZPAEvent: *azure_as_is_custom
  ZeroFoxAlertPoller_CL: *azure_as_is_custom
  ZoomLogs: *azure_as_is_custom
  _ASim_FileEvent: *azure_as_is_custom
  _ASim_ProcessEvent: *azure_as_is_custom
  _ASim_ProcessEvent_Create: *azure_as_is_custom
  _ASim_RegistryEvent: *azure_as_is_custom
  _Im_Dns: *azure_as_is_custom
  _Im_FileEvent: *azure_as_is_custom
  _Im_NetworkSession: *azure_as_is_custom
  _Im_ProcessEvent: *azure_as_is_custom
  _Im_WebSession: *azure_as_is_custom
  afad_parser: *azure_as_is_custom
  apifirewall_log_1_CL: *azure_as_is_custom
  atlassian_beacon_alerts_CL: *azure_as_is_custom
  AzureNetworkAnalytics_CL: *azure_as_is_custom
  blacklens_CL: *azure_as_is_custom
  corelight_conn: *azure_as_is_custom
  corelight_conn_red: *azure_as_is_custom
  corelight_dns: *azure_as_is_custom
  corelight_dns_red: *azure_as_is_custom
  corelight_files: *azure_as_is_custom
  corelight_http: *azure_as_is_custom
  corelight_smb_mapping: *azure_as_is_custom
  corelight_smtp: *azure_as_is_custom
  darktrace_model_alerts_CL: *azure_as_is_custom
  datatable: *azure_as_is_custom
  datawizaserveraccess_CL: *azure_as_is_custom
  dsp_parser: *azure_as_is_custom
  eset_CL: *azure_as_is_custom
  fluentbit_CL: *azure_as_is_custom
  http_proxy_oab_CL: *azure_as_is_custom
  imRegistry: *azure_as_is_custom
  imNetworkSession: *azure_as_is_custom
  jamfprotectalerts_CL: *azure_as_is_custom
  prancer_CL: *azure_as_is_custom
  secRMM_CL: *azure_as_is_custom
  test: *azure_as_is_custom
  vCenter: *azure_as_is_custom
